In [2]:
import numpy as np

In [4]:
array_1D = np.array([4, 5, 7, 10])
print(array_1D)
type(array_1D)

[ 4  5  7 10]


numpy.ndarray

In [5]:
array_2 = np.array([[4, 5], [7, 10]])
print(array_2)

[[ 4  5]
 [ 7 10]]


In [10]:
print("Array 1D Mean: ", array_1D.mean())
print("Array 2D Mean: ", array_2.mean())
print("Array 2D Row Wise Mean: ", np.mean(array_2, axis = 1))
print("Array 2D Col Wise Mean: ", np.mean(array_2, axis = 0))

Array 1D Mean:  6.5
Array 2D Mean:  6.5
Array 2D Row Wise Mean:  [4.5 8.5]
Array 2D Col Wise Mean:  [5.5 7.5]


In [11]:
print("Array 2D Row Wise Mean: ", np.mean(array_2, axis = 1, dtype=int))
print("Array 2D Col Wise Mean: ", np.mean(array_2, axis = 0, dtype=int))

Array 2D Row Wise Mean:  [4 8]
Array 2D Col Wise Mean:  [5 7]


In [13]:
array_1D = np.array([10, 11, 12, 13, 14])
array_2D = np.array([[20, 30, 40, 50, 60], [43, 54, 65, 76, 87], [11, 22, 33, 44, 55]])
array_3D = np.array([[[1, 2, 3, 4, 5], [11, 21, 31, 41, 51]], [[11, 12, 13, 14, 15],[51, 52, 53, 54, 5]]])


In [14]:
array_1D

array([10, 11, 12, 13, 14])

In [15]:
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [16]:
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

In [20]:
array_1D[0]

10

In [24]:
array_2D[0]

array([20, 30, 40, 50, 60])

In [25]:
array_3D[0]

array([[ 1,  2,  3,  4,  5],
       [11, 21, 31, 41, 51]])

In [26]:
array_2D[0, 0]

20

In [27]:
array_3D[0, 0, 0]

1

In [30]:
array_1D[-1]

14

In [32]:
array_2D[-1]

array([11, 22, 33, 44, 55])

In [33]:
array_3D[-1]

array([[11, 12, 13, 14, 15],
       [51, 52, 53, 54,  5]])

In [44]:
array_1D[-2] = 10
print(array_1D)

[10 11 12 10 14]


In [45]:
array_2D[-1, -2] = 10
print(array_2D)

[[20 30 40 50 60]
 [43 54 65 76 87]
 [11 22 33 10 55]]


In [46]:
array_3D[-1, -1, -2] = 10
print(array_3D)

[[[ 1  2  3  4  5]
  [11 21 31 41 51]]

 [[11 12 13 14 15]
  [51 52 53 10  5]]]


In [47]:
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 10, 55]])

In [63]:
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 10, 55]])

In [69]:
array_2D[:, -1] = 100
array_2D

array([[ 20,  30,  40,  50, 100],
       [ 43,  54,  65,  76, 100],
       [ 11,  22,  33,  10, 100]])

In [70]:
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 10,  5]]])

In [72]:
array_3D[:,:,:] = 1000

In [73]:
array_3D

array([[[1000, 1000, 1000, 1000, 1000],
        [1000, 1000, 1000, 1000, 1000]],

       [[1000, 1000, 1000, 1000, 1000],
        [1000, 1000, 1000, 1000, 1000]]])

In [74]:
array_2D

array([[ 20,  30,  40,  50, 100],
       [ 43,  54,  65,  76, 100],
       [ 11,  22,  33,  10, 100]])

In [75]:
array_2D+2

array([[ 22,  32,  42,  52, 102],
       [ 45,  56,  67,  78, 102],
       [ 13,  24,  35,  12, 102]])

In [76]:
array_2D

array([[ 20,  30,  40,  50, 100],
       [ 43,  54,  65,  76, 100],
       [ 11,  22,  33,  10, 100]])

In [77]:
array_3D

array([[[1000, 1000, 1000, 1000, 1000],
        [1000, 1000, 1000, 1000, 1000]],

       [[1000, 1000, 1000, 1000, 1000],
        [1000, 1000, 1000, 1000, 1000]]])

In [79]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
print(array_3D*100)

[[[ 100  200  300  400  500]
  [1100 2100 3100 4100 5100]]

 [[1100 1200 1300 1400 1500]
  [5100 5200 5300 5400  500]]]


In [80]:
array_1D = np.array([10,11,12,13,14])
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])

In [81]:
print(array_1D + array_2D[0])

array([30, 41, 52, 63, 74])

In [86]:
print(array_1D * array_2D[1])

[ 430  594  780  988 1218]


In [87]:
print(array_2D[2] - array_3D[1, 1])

[-40 -30 -20 -10  50]


In [92]:
array_1D = np.array([10,11,12,13,14], dtype = str)
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]], dtype = float)

In [90]:
array_1D

array(['10', '11', '12', '13', '14'], dtype='<U2')

In [93]:
array_2D

array([[20., 30., 40., 50., 60.],
       [43., 54., 65., 76., 87.],
       [11., 22., 33., 44., 55.]])

In [96]:
array_1D = np.array([10,11,12,13,14], dtype = str)
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]], dtype = np.float32)

In [97]:
array_1D

array(['10', '11', '12', '13', '14'], dtype='<U2')

In [98]:
array_2D

array([[20., 30., 40., 50., 60.],
       [43., 54., 65., 76., 87.],
       [11., 22., 33., 44., 55.]], dtype=float32)

In [100]:
array_1D = np.array([10,11,12,13,14], dtype = np.float32)
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]], dtype = np.float32)

In [101]:
array_3D / array_1D

array([[[0.1       , 0.18181819, 0.25      , 0.30769232, 0.35714287],
        [1.1       , 1.9090909 , 2.5833333 , 3.1538463 , 3.642857  ]],

       [[1.1       , 1.0909091 , 1.0833334 , 1.0769231 , 1.0714285 ],
        [5.1       , 4.7272725 , 4.4166665 , 4.1538463 , 0.35714287]]],
      dtype=float32)

In [102]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]], dtype = np.float32)
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]], dtype = np.float32)

In [103]:
array_2D

array([[20., 30., 40., 50., 60.],
       [43., 54., 65., 76., 87.],
       [11., 22., 33., 44., 55.]], dtype=float32)

In [108]:
np.mean(array_2D, axis = 0, dtype = np.int64)

array([24, 35, 46, 56, 67], dtype=int64)

In [107]:
np.mean(array_3D, axis = 0)

array([[ 6. ,  7. ,  8. ,  9. , 10. ],
       [31. , 36.5, 42. , 47.5, 28. ]], dtype=float32)

In [109]:
array_3D

array([[[ 1.,  2.,  3.,  4.,  5.],
        [11., 21., 31., 41., 51.]],

       [[11., 12., 13., 14., 15.],
        [51., 52., 53., 54.,  5.]]], dtype=float32)

In [110]:
array_1D = np.array([10,11,12,13, 14])
array_1D

array([10, 11, 12, 13, 14])

In [111]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])

In [112]:
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [113]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

In [114]:
array_hw_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
array_hw_1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [116]:
type(array_hw_1)

numpy.ndarray

In [118]:
array_hw_1.shape

(8,)

In [119]:
array_hw_1.size

8

In [120]:
array_hw_2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
array_hw_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [122]:
type(array_hw_2)

numpy.ndarray

In [123]:
array_hw_2.shape

(2, 4)

In [124]:
array_hw_2.size

8

In [125]:
array_hw_3 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]]])
array_hw_3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [126]:
type(array_hw_3)

numpy.ndarray

In [127]:
array_hw_3.shape

(1, 2, 4)

In [128]:
array_hw_3.size

8

In [129]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]], dtype = np.float32)

In [130]:
array_2D

array([[20., 30., 40., 50., 60.],
       [43., 54., 65., 76., 87.],
       [11., 22., 33., 44., 55.]], dtype=float32)

In [165]:
#1. Slice the first column of the 2D array.
print(array_2D[:, :1].squeeze())

[20. 43. 11.]


In [151]:
# Slice the last column of the 2D array.
array_2D[:, -1:]

array([[60.],
       [87.],
       [55.]], dtype=float32)

In [152]:
#  Slice the second row of the 2D array.
array_2D[1:2, :]

array([[43., 54., 65., 76., 87.]], dtype=float32)

In [155]:
#4. Slice the last two columns of the second row of the 2D array.
array_2D[1:2, -2:]

array([[76., 87.]], dtype=float32)

In [157]:
# 5. Slice the second row of the 2D array excluding the last two columns
array_2D[1:2, :-2]

array([[43., 54., 65.]], dtype=float32)

In [160]:
# 6. Slice everything except the first row and last column of the 2D array.
array_2D[1:, :-1]

array([[43., 54., 65., 76.],
       [11., 22., 33., 44.]], dtype=float32)

In [162]:
# 7. Slice the 1st, 3rd and 5th columns of the 2D array.
array_2D[:, ::2]

array([[20., 40., 60.],
       [43., 65., 87.],
       [11., 33., 55.]], dtype=float32)

In [166]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])

In [167]:
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

In [170]:
# 1. Slice the first column of both matrices in the 3D array.
array_3D[:, :, :1].squeeze()

array([[ 1, 11],
       [11, 51]])

In [172]:
# 2. Slice every other column of both matrices in the 3D array.
array_3D[:, :, ::2].squeeze()

array([[[ 1,  3,  5],
        [11, 31, 51]],

       [[11, 13, 15],
        [51, 53,  5]]])

In [174]:
array_1D = np.array([10,11,12,13,14])
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])

In [175]:
# 1. Use a conditional expression on array_1D as the argument to the given print() function to check which elements are greater than 10.
array_1D > 10

array([False,  True,  True,  True,  True])

In [176]:
# 2. Use a conditional expression on array_2D as the argument to the given print() function to check which elements are greater than 10.
array_2D > 10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [177]:
# 3. Use a conditional expression on array_3D as the argument to the given print() function to check which elements are greater than 10.
array_3D > 10

array([[[False, False, False, False, False],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True, False]]])

In [181]:
# 1. Use conditional slicing on array_1D as the argument to the given print() function to extract the elements greater than 10.
array_1D[array_1D > 10]

array([11, 12, 13, 14])

In [182]:
# 2. Use conditional slicing on array_2D as the argument to the given print() function to extract the elements greater than 10.
array_2D[array_2D > 10]

array([20, 30, 40, 50, 60, 43, 54, 65, 76, 87, 11, 22, 33, 44, 55])

In [183]:
# 3. Use conditional slicing on array_3D as the argument to the given print() function to extract the elements greater than 10.
array_3D[array_3D > 10]

array([11, 21, 31, 41, 51, 11, 12, 13, 14, 15, 51, 52, 53, 54])

In [191]:
# 1. Use conditional slicing on array_1D as the argument to the given print() function to extract the odd values greater than 10.
array_1D[((array_1D > 10) & (array_1D % 2 == 1))]

array([11, 13])

In [192]:
# 2. Use conditional slicing on array_2D as the argument to the given print() function to extract the odd values greater than 10.
array_2D[((array_2D > 10) & (array_2D % 2 == 1))]

array([43, 65, 87, 11, 33, 55])

In [193]:
# 3. Use conditional slicing on array_3D as the argument to the given print() function to extract the odd values greater than 10.
array_3D[((array_3D > 10) & (array_3D % 2 == 1))]

array([11, 21, 31, 41, 51, 11, 13, 15, 51, 53])

In [195]:
# 1. Use conditional slicing on array_1D as the argument to the given print() function to extract the values that are either odd, greater than 10, or both.
array_1D[((array_1D > 10) | (array_1D % 2 == 1))]

array([11, 12, 13, 14])

In [196]:
# 2. Use conditional slicing on array_2D as the argument to the given print() function to extract the values that are either odd, greater than 10, or both.
array_2D[((array_2D > 10) | (array_2D % 2 == 1))]

array([20, 30, 40, 50, 60, 43, 54, 65, 76, 87, 11, 22, 33, 44, 55])

In [197]:
# 3. Use conditional slicing on array_3D as the argument to the given print() function to extract the values that are either odd, greater than 10, or both.
array_3D[((array_3D > 10) | (array_3D % 2 == 1))]

array([ 1,  3,  5, 11, 21, 31, 41, 51, 11, 12, 13, 14, 15, 51, 52, 53, 54,
        5])

In [198]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])

In [199]:
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

In [202]:
# Access the first row of the first 2D array in array_3D using exact indices for both dimensions.
array_3D[0, 0]

array([1, 2, 3, 4, 5])

In [203]:
# Check the shape of the resulting object.
array_3D[0, 0].shape

(5,)

In [216]:
array_3D[:1, 0]

array([[1, 2, 3, 4, 5]])

In [217]:
array_3D[:1, 0].shape

(1, 5)

In [218]:
array_3D[:1, :1]

array([[[1, 2, 3, 4, 5]]])

In [219]:
array_3D[:1, :1].shape

(1, 1, 5)

In [220]:
array_3D[:1,0]

array([[1, 2, 3, 4, 5]])

In [224]:
array_3D[:1,0].shape

(1, 5)

In [222]:
array_3D[:1,0].squeeze()

array([1, 2, 3, 4, 5])

In [223]:
array_3D[:1,0].squeeze().shape

(5,)

In [225]:
#1.
print(np.squeeze(array_3D[:1,0]))
#2.
print(np.squeeze(array_3D[:1,0]).shape)

[1 2 3 4 5]
(5,)


In [231]:
# Beginner Level From Chatgpt
# 1. Create a 1D NumPy array of numbers from 0 to 9
gpt_1D = np.arange(start = 0, stop = 9, dtype = np.int8)
gpt_1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int8)

In [230]:
# 2. Create a 2D array of shape (3, 3) with all zeros.
gpt_2D = np.zeros(shape = (3, 3), dtype = np.int8)
gpt_2D

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [232]:
# 3. Create a 2D array of shape (2, 4) filled with ones.
gpt_2D_2 = np.ones(shape = (2, 4), dtype = np.int8)
gpt_2D_2

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [239]:
# 4. Create an identity matrix of size 4x4.
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [241]:
# 5. Generate an array with numbers from 10 to 20 (inclusive).
np.arange(start = 10, stop = 21, dtype = np.int8)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], dtype=int8)

In [246]:
# 6. Create an array of 5 random integers between 1 and 10.
np.random.randint(1, 11, size = 5)

array([7, 3, 4, 4, 1])

In [247]:
# 7. Get the shape, size, and data type of the array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.size)
print(arr.dtype)

(2, 3)
6
int32


In [252]:
# 8. Convert a list to a NumPy array.
data = [10, 20, 30]
np.array(data)

array([10, 20, 30])

In [259]:
# 9. Change array data type from int to float.
arr.astype(float)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [261]:
# 10. Reshape a 1D array of 12 elements into 3x4.
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [264]:
# 11. Find the maximum value in the array.
arr = np.array([1, 7, 3])
np.max(arr)

7

In [267]:
#12. Find the minimum and mean.
arr = np.array([[1, 2], [3, 4]])
print("Min: ", np.min(arr))
print("mean: ", np.mean(arr))
print("Size: ", np.size(arr))
print("Shape: ", np.shape(arr))

Min:  1
mean:  2.5
Size:  4
Shape:  (2, 2)


In [268]:
# 13. Find the sum of all elements.
arr = np.array([[1, 2], [3, 4]])
print("Sum: ", np.sum(arr))

Sum:  10


In [270]:
# 14. Slice to get only the last column.
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[:, -1:]

array([[3],
       [6]])

In [271]:
# 15. Reverse an array.
arr = np.array([1, 2, 3])
arr[::-1]

array([3, 2, 1])

In [277]:
np.full(10, fill_value=2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [278]:
array_1D = np.array([10,11,12,13, 14])
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])

In [279]:
print(np.empty_like(array_1D))

[   65537 16843009    65793 16842753 16777472]


In [280]:
print(np.zeros_like(array_2D))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [281]:
print(np.ones_like(array_3D))

[[[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]]


In [282]:
print(np.full_like(array_3D, fill_value=2))

[[[2 2 2 2 2]
  [2 2 2 2 2]]

 [[2 2 2 2 2]
  [2 2 2 2 2]]]


In [290]:
np.arange(start = 0, stop = 50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [285]:
np.arange(start = 1, stop = 51, dtype = np.int8)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
      dtype=int8)

In [286]:
np.arange(start = 25, stop = 51, dtype = np.int8)

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50], dtype=int8)

In [288]:
np.arange(start = 25, stop = 51, step = 5, dtype = np.int8)

array([25, 30, 35, 40, 45, 50], dtype=int8)

In [295]:
np.arange(start = 25, stop = 51, step = 5, dtype = np.float32)

array([25., 30., 35., 40., 45., 50.], dtype=float32)

In [303]:
np.arange(25, 51, 5).astype(float)

array([25., 30., 35., 40., 45., 50.])

In [296]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [297]:
array_RG = gen(pcg())
array_RG

Generator(PCG64) at 0x1FB02859EE0

In [298]:
array_RG.random()

0.8313951358793731

In [299]:
array_RG.random(10)

array([0.74240469, 0.85887953, 0.48155426, 0.97482894, 0.41281143,
       0.34241174, 0.28470434, 0.70714873, 0.34608805, 0.63685499])

In [301]:
array_RG.random((5, 10))

array([[0.32989893, 0.69246212, 0.61586078, 0.38711286, 0.93922971,
        0.00212384, 0.37176316, 0.67119433, 0.39029284, 0.72268419],
       [0.13842162, 0.53235759, 0.67400607, 0.38739278, 0.71153644,
        0.15116875, 0.76184463, 0.6875829 , 0.12370635, 0.18043173],
       [0.99258014, 0.14928981, 0.88522266, 0.52813137, 0.06928507,
        0.51487008, 0.01868038, 0.18947367, 0.20650637, 0.93177084],
       [0.1940774 , 0.04890169, 0.41604111, 0.12302649, 0.51830702,
        0.05281133, 0.73626075, 0.4358819 , 0.75785232, 0.83751665],
       [0.42103662, 0.80547951, 0.82408044, 0.36837026, 0.49525393,
        0.03912497, 0.74160411, 0.31901723, 0.89771602, 0.11708461]])

In [306]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

array_RG = gen(pcg(123))

In [307]:
print(array_RG.random((5, 10)))

[[0.68235186 0.05382102 0.22035987 0.18437181 0.1759059  0.81209451
  0.923345   0.2765744  0.81975456 0.88989269]
 [0.51297046 0.2449646  0.8242416  0.21376296 0.74146705 0.6299402
  0.92740726 0.23190819 0.79912513 0.51816504]
 [0.23155562 0.16590399 0.49778897 0.58272464 0.18433799 0.01489492
  0.47113323 0.72824333 0.91860049 0.62553401]
 [0.91712257 0.86469025 0.21814287 0.86612743 0.73075194 0.27786529
  0.79704355 0.86522171 0.2994379  0.52704208]
 [0.07148681 0.58323841 0.2379064  0.76496365 0.17363164 0.31274226
  0.01447448 0.03255192 0.49670184 0.46831253]]


In [312]:
array_RG = gen(pcg(123))
print(array_RG.integers(0, 10, 10))

[0 6 5 0 9 2 2 1 3 1]


In [313]:
print(array_RG.integers(0, 10, (5, 10)))

[[3 8 4 9 4 2 7 8 8 8]
 [0 5 2 2 2 8 7 2 4 7]
 [1 6 4 9 7 2 8 7 2 5]
 [7 2 2 1 0 4 0 5 4 1]
 [3 0 1 4 0 7 2 9 1 6]]


In [3]:
print(np.__version__)

1.26.4


In [4]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

#1.
array_RG = gen(pcg(123))
#2.
print(array_RG.integers(0, 10, 10))

[0 6 5 0 9 2 2 1 3 1]


In [7]:
array_RG = gen(pcg(123))
print(array_RG.integers(0, 10, (5, 10)))

[[0 6 5 0 9 2 2 1 3 1]
 [3 8 4 9 4 2 7 8 8 8]
 [0 5 2 2 2 8 7 2 4 7]
 [1 6 4 9 7 2 8 7 2 5]
 [7 2 2 1 0 4 0 5 4 1]]


In [8]:
print(array_RG.integers(10, size = (5, 10)))

[[3 0 1 4 0 7 2 9 1 6]
 [5 9 6 8 4 2 1 8 2 7]
 [5 2 4 7 4 8 9 2 5 5]
 [5 0 3 5 9 2 6 7 9 1]
 [6 3 4 0 7 0 3 4 6 4]]


In [10]:
print(array_RG.random((5, 10)))

[[0.12769032 0.2575625  0.00318111 0.38106775 0.57587308 0.42729877
  0.83510235 0.61649125 0.26608391 0.81102211]
 [0.49948675 0.75881032 0.56608909 0.43744036 0.39615444 0.02223529
  0.46935079 0.6235584  0.94611342 0.43532608]
 [0.4856414  0.51911514 0.40859098 0.57879572 0.07035067 0.48838383
  0.61014483 0.74387911 0.42983032 0.30280213]
 [0.00589003 0.75647897 0.07757597 0.48998804 0.3043611  0.84082216
  0.95047586 0.31887458 0.89776829 0.33752905]
 [0.81211211 0.7988436  0.65528518 0.22870345 0.13767446 0.42437114
  0.15153875 0.87327295 0.17912676 0.03029466]]


In [16]:
array_RG = gen(pcg(seed = 123))

In [25]:
print(array_RG.normal())

0.9913261626706856


In [27]:
print(array_RG.poisson(lam=15, size = 10))

[20 11  8 12 12 14 11 13 13 17]


In [20]:
print(array_RG.binomial(n=100, p=0.70, size=(5, 10)))

[[73 70 71 64 64 73 73 65 76 69]
 [79 74 73 74 65 65 64 73 77 70]
 [69 78 67 75 73 69 70 72 66 68]
 [68 71 66 70 72 70 67 72 65 71]
 [74 69 77 73 64 68 69 61 72 59]]


In [28]:
import numpy as np

np.set_printoptions(suppress = True, linewidth = 150, precision = 2)

array_1D = np.array([10,11,12,13,14])
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])

In [29]:
np.max(array_1D)

14

In [30]:
np.amax(array_2D)

87

In [32]:
np.amax(array_1D, axis = 0)

14

In [33]:
np.amax(array_2D, axis = 1)

array([60, 87, 55])

In [35]:
np.amax(array_3D, axis = 2)

array([[ 5, 51],
       [15, 54]])

In [36]:
np.maximum.reduce(array_1D)

14

In [37]:
np.maximum.reduce(array_3D)

array([[11, 12, 13, 14, 15],
       [51, 52, 53, 54, 51]])

In [38]:
np.ptp(array_1D)

4

In [40]:
np.ptp(array_2D)

76

In [41]:
np.ptp(array_3D)

53

In [42]:
print(np.ptp(array_1D))
#2.
print(np.ptp(array_2D))
#3.
print(np.ptp(array_3D))
#4.
print(np.ptp(array_2D, axis = 1))
#5.
print(np.ptp(array_3D, axis = 2))

4
76
53
[40 44 44]
[[ 4 40]
 [ 4 49]]


In [43]:
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [45]:
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

In [74]:
np.set_printoptions(suppress = True, linewidth = 150, precision = 2)

array_1D = np.array([10,11,12,13,14])
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])

In [48]:
array_1D.sort()

In [49]:
array_1D

array([10, 11, 12, 13, 14])

In [50]:
np.sort(array_1D)

array([10, 11, 12, 13, 14])

In [52]:
np.percentile(array_1D, q = 30)

11.2

In [54]:
np.quantile(array_1D, q = 0.66)

12.64

In [55]:
np.quantile(array_1D, q = 0.5)

12.0

In [56]:
array_2D = np.sort(array_2D)
print(np.percentile(array_2D, q = 30))
print(np.quantile(array_2D, q = 0.66))
print(np.quantile(array_2D, q = 0.5))

34.4
54.24
44.0


In [58]:
array_3D = np.sort(array_3D)
print(np.percentile(array_3D, q = 30))
print(np.quantile(array_3D, q = 0.66))
print(np.quantile(array_3D, q = 0.5))

9.200000000000001
26.40000000000001
13.5


In [59]:
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [ 5, 51, 52, 53, 54]]])

In [71]:
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [72]:
array_2D.sort()

In [73]:
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [75]:
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [76]:
np.sort(array_2D)

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [77]:
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [78]:
array_2D = np.array([
    [20,30,40,50,60], 
    [43,54,65,76,87], 
    [11,22,33,44,55]
])

In [80]:
# 1. Mean.
print(np.mean(array_2D))
# 2. Median.
print(np.median(array_2D))
# 3. Column-wise mean.
print(np.mean(array_2D, 0))
# 4. Variance.
print(np.var(array_2D))
# 5. Standard deviation.
print(np.std(array_2D))
# 6. Covariance (treating each row as a variable and each column as an observation).
print(np.cov(array_2D))
# 7. Correlation (treating each row as a variable and each column as an observation).
print(np.corrcoef(array_2D))

46.0
44.0
[24.67 35.33 46.   56.67 67.33]
416.6666666666667
20.412414523193153
[[250.  275.  275. ]
 [275.  302.5 302.5]
 [275.  302.5 302.5]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [81]:
#1.
print(np.mean(array_2D))
#2.
print(np.median(array_2D))
#3.
print(np.median(array_2D, axis = 0))
#4.
print(np.var(array_2D))
#5.
print(np.std(array_2D))
#6.
print(np.cov(array_2D))
#7.
print(np.corrcoef(array_2D))

46.0
44.0
[20. 30. 40. 50. 60.]
416.6666666666667
20.412414523193153
[[250.  275.  275. ]
 [275.  302.5 302.5]
 [275.  302.5 302.5]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [83]:
import numpy as np

array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])

#1.
x_vals = array_2D[0]
y_vals = array_2D[1]
result_2d = np.histogram2d(x_vals, y_vals, bins=4)[0]
#2.
points_3D = array_2D.T
result_dd = np.histogramdd(points_3D, bins=4)[0]

In [84]:
result_2d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 2.]])

In [85]:
result_dd

array([[[1., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 2.]]])

In [86]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])

#1.
result_2d = np.histogram2d(array_2D[0], array_2D[1], bins=4)

#2.
result_dd = np.histogramdd(array_2D.T, bins=4)

In [87]:
result_2d

(array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 2.]]),
 array([20., 30., 40., 50., 60.]),
 array([43., 54., 65., 76., 87.]))

In [88]:
result_dd

(array([[[1., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 2.]]]),
 [array([20., 30., 40., 50., 60.]),
  array([43., 54., 65., 76., 87.]),
  array([11., 22., 33., 44., 55.])])

In [89]:
array_nan = np.array([
    [20,    np.nan, 40, 50,     60], 
    [np.nan,54,     65, np.nan, 87], 
    [11,    22,     33, 44,     np.nan]
])

In [92]:
np.mean(array_nan)

nan

In [93]:
np.nanmean(array_nan)

44.18181818181818

In [94]:
np.var(array_nan)

nan

In [95]:
np.nanvar(array_nan)

451.6033057851239

In [96]:
# How do you create a NumPy array of shape (3, 4) filled with zeros?
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [99]:
np.arange(10, 21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [101]:
arr = np.arange(1, 13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [102]:
arr.reshape((3, 4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [104]:
arr > 10

array([False, False, False, False, False, False, False, False, False, False,  True,  True])

In [105]:
np.where(arr > 10)

(array([10, 11], dtype=int64),)

In [106]:
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [109]:
array_2D.mean(axis = 1)

array([40., 65., 33.])

In [125]:
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [126]:
arr2d = array_2D - 50
arr2d

array([[-30, -20, -10,   0,  10],
       [ -7,   4,  15,  26,  37],
       [-39, -28, -17,  -6,   5]])

In [123]:
arr2d = np.where(arr2d<0, 0, arr2d)
arr2d

array([[ 0,  0,  0,  0, 10],
       [ 0,  4, 15, 26, 37],
       [ 0,  0,  0,  0,  5]])

In [127]:
arr2d

array([[-30, -20, -10,   0,  10],
       [ -7,   4,  15,  26,  37],
       [-39, -28, -17,  -6,   5]])

In [129]:
arr2d[arr2d < 0] = 0

In [130]:
arr2d

array([[ 0,  0,  0,  0, 10],
       [ 0,  4, 15, 26, 37],
       [ 0,  0,  0,  0,  5]])

In [131]:
array_1D

array([10, 11, 12, 13, 14])

In [133]:
np.random

<module 'numpy.random' from 'C:\\Users\\Karthik\\anaconda3\\Lib\\site-packages\\numpy\\random\\__init__.py'>

In [134]:
arr = np.random.randint(1, 101, 10)

In [135]:
arr

array([70, 64, 58, 16, 76, 25, 41, 63, 49,  7])

In [136]:
top3 = np.partition(arr, -3)[-3:]
top3

array([64, 70, 76])

In [137]:
np.mod(array_1D)

TypeError: remainder() takes from 2 to 3 positional arguments but 1 were given

In [138]:
vals, counts = np.unique(arr, return_counts=True)
mode = vals[np.argmax(counts)]

In [139]:
mode

7

In [140]:
vals

array([ 7, 16, 25, 41, 49, 58, 63, 64, 70, 76])

In [141]:
counts

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [146]:
data = [10, 20, 30, 40, 50]
np.array(data)

array([10, 20, 30, 40, 50])

In [147]:
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [149]:
np.sum(array_2D, axis = 0)

array([ 74, 106, 138, 170, 202])

In [152]:
np.isnan(arr).any()

False

In [153]:
arr

array([70, 64, 58, 16, 76, 25, 41, 63, 49,  7])

In [154]:
arr2d

array([[ 0,  0,  0,  0, 10],
       [ 0,  4, 15, 26, 37],
       [ 0,  0,  0,  0,  5]])

In [159]:
import numpy as np

# Create a random array of shape (4, 5)
arr = np.random.randint(1, 100, size=(4, 5)).astype(float)

# Set 5 random positions to NaN
num_nan = 5
rows, cols = arr.shape
nan_indices = np.random.choice(rows * cols, size=num_nan, replace=False)

# Convert 1D indices to 2D indices
row_indices, col_indices = np.unravel_index(nan_indices, (rows, cols))
arr[row_indices, col_indices] = np.nan

print(arr)


[[17. 73. 82. nan 21.]
 [nan 26. 96. 73. nan]
 [72. 54. 76. 39. 25.]
 [nan nan 98. 19.  4.]]


In [162]:
arr[~np.isnan(arr)]

array([17., 73., 82., 21., 26., 96., 73., 72., 54., 76., 39., 25., 98., 19.,  4.])

In [158]:
arr1

array([[False, False,  True, False, False],
       [ True, False, False, False,  True],
       [False,  True, False, False, False],
       [False, False, False, False,  True]])

In [163]:
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [167]:
array_2D[np.argmax(np.sum(array_2D, axis = 1))]

array([43, 54, 65, 76, 87])

In [168]:
arr

array([[17., 73., 82., nan, 21.],
       [nan, 26., 96., 73., nan],
       [72., 54., 76., 39., 25.],
       [nan, nan, 98., 19.,  4.]])

In [170]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [172]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [173]:
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [174]:
array_2D.flatten()

array([20, 30, 40, 50, 60, 43, 54, 65, 76, 87, 11, 22, 33, 44, 55])

In [176]:
array_2D.T

array([[20, 43, 11],
       [30, 54, 22],
       [40, 65, 33],
       [50, 76, 44],
       [60, 87, 55]])

In [177]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [178]:
matrix[1]

array([4, 5, 6])

In [180]:
matrix[:, 1]

array([2, 5])

In [181]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [182]:
matrix > 3

array([[False, False, False],
       [ True,  True,  True]])

In [183]:
matrix[matrix > 3]

array([4, 5, 6])

In [184]:
matrix[matrix % 2 == 0]

array([2, 4, 6])

In [185]:
np.where(matrix > 3, "High", "Low")

array([['Low', 'Low', 'Low'],
       ['High', 'High', 'High']], dtype='<U4')

In [186]:
np.where(matrix % 2 == 0, "Even", "Odd")

array([['Odd', 'Even', 'Odd'],
       ['Even', 'Odd', 'Even']], dtype='<U4')

In [187]:
arr = np.array([10, 20, 30, 40, 50, 60])

In [189]:
arr.reshape(3, 2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [190]:
arr.flatten()

array([10, 20, 30, 40, 50, 60])

In [191]:
arr.ravel()

array([10, 20, 30, 40, 50, 60])

In [192]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [193]:
a

array([1, 2, 3])

In [194]:
b

array([4, 5, 6])

In [195]:
np.hstack([a, b])

array([1, 2, 3, 4, 5, 6])

In [196]:
np.vstack([a, b])

array([[1, 2, 3],
       [4, 5, 6]])

In [197]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

In [198]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [199]:
np.hsplit(arr, 2)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [200]:
np.vsplit(arr, 2)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [203]:
np.hsplit(arr, 4)

[array([[1],
        [5]]),
 array([[2],
        [6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [204]:
x = np.array([[10, 20, 30],
              [40, 50, 60]])
y = np.array([[70, 80, 90],
              [100, 110, 120]])

In [205]:
x

array([[10, 20, 30],
       [40, 50, 60]])

In [206]:
y

array([[ 70,  80,  90],
       [100, 110, 120]])

In [207]:
np.hstack([x, y])

array([[ 10,  20,  30,  70,  80,  90],
       [ 40,  50,  60, 100, 110, 120]])

In [208]:
np.vstack([x, y])

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [211]:
np.hsplit(np.hstack([x, y]), 3)

[array([[10, 20],
        [40, 50]]),
 array([[ 30,  70],
        [ 60, 100]]),
 array([[ 80,  90],
        [110, 120]])]

In [212]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])

In [213]:
a + b

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [217]:
np.shape(a)

(3, 1)

In [218]:
a

array([[1],
       [2],
       [3]])

In [219]:
b

array([10, 20, 30])

In [224]:
arr2d = np.array([[12, 25, 7],
                  [30, 18, 5],
                  [22, 9, 40]])

# Q3: Replace all values < 20 with 0 (in-place)
arr2d[arr2d < 20] = 0
arr2d

array([[ 0, 25,  0],
       [30,  0,  0],
       [22,  0, 40]])

In [222]:
np.where(arr2d < 20 , 0, arr2d)

array([[ 0, 25,  0],
       [30,  0,  0],
       [22,  0, 40]])

In [227]:
arr2d = np.array([[12, 25, 7],
                  [30, 18, 5],
                  [22, 9, 40]])

# Q4: Extract values where 10 ≤ x ≤ 30
arr2d[(arr2d >= 10) & (arr2d <= 30)]

array([12, 25, 30, 18, 22])

In [234]:
arr_nan = np.array([[12, np.nan, 7],
                    [30, 18, np.nan],
                    [np.nan, 9, 40]])

# Q7a: Column-wise mean, ignoring NaNs
print(np.nanmean(arr_nan, axis = 0))
# Q7b: Count of NaNs in entire array
print(np.sum(np.isnan(arr_nan)))

[21.  13.5 23.5]
3


In [235]:
arr_nan

array([[12., nan,  7.],
       [30., 18., nan],
       [nan,  9., 40.]])

In [236]:
col_means = np.nanmean(arr_nan, axis = 0)
print(col_means)

[21.  13.5 23.5]


In [239]:
filled_array = np.where(np.isnan(arr_nan), col_means, arr_nan)
filled_array

array([[12. , 13.5,  7. ],
       [30. , 18. , 23.5],
       [21. ,  9. , 40. ]])

In [240]:
arr_nan = np.array([[12, np.nan, 7],
                    [30, 18, np.nan],
                    [np.nan, 9, 40]])
arr_nan

array([[12., nan,  7.],
       [30., 18., nan],
       [nan,  9., 40.]])

In [259]:
row_mean = np.nanmean(arr_nan, axis = 1)
print(row_mean)
print(np.shape(row_mean))
print(np.reshape(row_mean, (1, 3)).T)

[ 9.5 24.  24.5]
(3,)
[[ 9.5]
 [24. ]
 [24.5]]


In [252]:
np.reshape(row_mean, (1, 3))

array([[ 9.5, 24. , 24.5]])

In [260]:
np.where(np.isnan(arr_nan), np.reshape(row_mean, (1, 3)).T, arr_nan)

array([[12. ,  9.5,  7. ],
       [30. , 18. , 24. ],
       [24.5,  9. , 40. ]])

In [261]:
arr_nan

array([[12., nan,  7.],
       [30., 18., nan],
       [nan,  9., 40.]])

In [262]:
row_mean

array([ 9.5, 24. , 24.5])

In [263]:
row_mean[:, np.newaxis]

array([[ 9.5],
       [24. ],
       [24.5]])

In [264]:
a = np.array([10, 20, 30])         # shape: (3,)
b = np.array([[1], [2], [3]])      # shape: (3, 1)

# Broadcasting works because:
a_col = a[:, np.newaxis]           # shape: (3, 1)

result = a_col * b                 # shape: (3, 1) * (3, 1) = (3, 1)

In [265]:
a_col

array([[10],
       [20],
       [30]])

In [266]:
a

array([10, 20, 30])

In [267]:
result

array([[10],
       [40],
       [90]])

In [268]:
b

array([[1],
       [2],
       [3]])

In [270]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# Q: Select elements at positions (0,2), (1,1), and (2,0)
rows = [0, 1, 2]
cols = [2, 1, 0]
arr[rows, cols]

array([30, 50, 70])

In [271]:
arr2d = np.array([[5, 10], [15, 20]])
np.where(arr2d > 10)

(array([1, 1], dtype=int64), array([0, 1], dtype=int64))

In [272]:
arr = np.array([[10, 25, 30],
                [45, 50, 60],
                [70, 80, 90]])

# Replace all values > 50 with 999
np.where(arr > 50, 999, arr)

array([[ 10,  25,  30],
       [ 45,  50, 999],
       [999, 999, 999]])

In [274]:
arr

array([[10, 25, 30],
       [45, 50, 60],
       [70, 80, 90]])

In [273]:
np.where((arr > 30) & (arr < 80), 1, 0)

array([[0, 0, 0],
       [1, 1, 1],
       [1, 0, 0]])

In [275]:
np.where((arr < 20) | (arr > 80), -1, arr)


array([[-1, 25, 30],
       [45, 50, 60],
       [70, 80, -1]])

In [276]:
arr

array([[10, 25, 30],
       [45, 50, 60],
       [70, 80, 90]])

In [277]:
mean_val = arr[(arr >= 20) & (arr <= 80)].mean()
np.where((arr < 20) | (arr > 80), mean_val, arr)

array([[51.43, 25.  , 30.  ],
       [45.  , 50.  , 60.  ],
       [70.  , 80.  , 51.43]])

In [278]:
arr[(arr >= 20) & (arr <= 80)]

array([25, 30, 45, 50, 60, 70, 80])

In [279]:
arr

array([[10, 25, 30],
       [45, 50, 60],
       [70, 80, 90]])

In [280]:
np.where(arr < 30, 0,
         np.where(arr <= 70, 1, 2))

array([[0, 0, 1],
       [1, 1, 1],
       [1, 2, 2]])

In [1]:
import numpy as np

In [31]:
arr = np.array([[10, 25, 30],
                [45, 50, 60],
                [70, 80, 90]])

In [4]:
arr.ndim

2

In [5]:
arr[arr > 30]

array([45, 50, 60, 70, 80, 90])

In [6]:
np.sum(arr, axis = 0)

array([125, 155, 180])

In [7]:
arr

array([[10, 25, 30],
       [45, 50, 60],
       [70, 80, 90]])

In [10]:
arr[1:, :2] = 10

In [11]:
arr

array([[10, 25, 30],
       [10, 10, 60],
       [10, 10, 90]])

In [12]:
arr

array([[10, 25, 30],
       [10, 10, 60],
       [10, 10, 90]])

In [14]:
arr[arr % 2 != 0]

array([25])

In [15]:
np.array([1, 2, 3]) + np.array([[1],[2],[3]])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [20]:
np.ndim(np.array([[1],[2],[3]]))

2

In [22]:
np.arange(10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [29]:
np.tile(np.array([1, 2]),(2, 3))

array([[1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2]])

In [27]:
np.array([1, 2])

array([1, 2])

In [30]:
arr

array([[10, 25, 30],
       [10, 10, 60],
       [10, 10, 90]])

In [33]:
np.all(arr > 0)

True

In [34]:
np.cumsum(np.array([1, 2, 3]))

array([1, 3, 6])

In [35]:
np.cumproduct(np.array([1, 2, 3]))

array([1, 2, 6])

In [37]:
np.cumprod(np.array([1, 4, 3]))

array([ 1,  4, 12])

In [39]:
np.random.randint(1, 10, size = (5, 5))

array([[5, 2, 1, 3, 6],
       [7, 9, 4, 4, 7],
       [5, 8, 3, 4, 9],
       [8, 8, 4, 6, 9],
       [2, 7, 3, 9, 3]])

In [40]:
arr

array([[10, 25, 30],
       [45, 50, 60],
       [70, 80, 90]])

In [41]:
np.clip(arr, 40, 50)

array([[40, 40, 40],
       [45, 50, 50],
       [50, 50, 50]])

In [42]:
arr

array([[10, 25, 30],
       [45, 50, 60],
       [70, 80, 90]])

In [43]:
np.expand_dims(arr, axis = 0)

array([[[10, 25, 30],
        [45, 50, 60],
        [70, 80, 90]]])

In [44]:
arr

array([[10, 25, 30],
       [45, 50, 60],
       [70, 80, 90]])

In [45]:
np.argsort(arr)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [48]:
np.prod(np.array([1, 5, 3]))

15

In [49]:
arr

array([[10, 25, 30],
       [45, 50, 60],
       [70, 80, 90]])

In [51]:
np.isin(arr, [25, 70])

array([[False,  True, False],
       [False, False, False],
       [ True, False, False]])

In [52]:
a = np.array([[1, 2], [3, 4]])

In [53]:
a

array([[1, 2],
       [3, 4]])

In [54]:
a.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4]])

In [55]:
a.reshape([1, -1])

array([[1, 2, 3, 4]])

In [58]:
a.reshape([-1, 4])

array([[1, 2, 3, 4]])

In [59]:
np.shape(a.reshape(-1, 1))

(4, 1)

In [60]:
np.shape(a.reshape(1, -1))

(1, 4)

In [62]:
a = np.array([1, 2, 3])
np.expand_dims(a, axis=0)  # → shape (1, 3)

array([[1, 2, 3]])

In [63]:
np.expand_dims(a, axis=1)

array([[1],
       [2],
       [3]])

In [64]:
a

array([1, 2, 3])

In [65]:
arr

array([[10, 25, 30],
       [45, 50, 60],
       [70, 80, 90]])

In [67]:
def even_odd(x):
    return "Even" if x % 2 == 0 else "Odd"
np.vectorize(even_odd)(np.array([1, 2, 3, 4, 5]))

array(['Odd', 'Even', 'Odd', 'Even', 'Odd'], dtype='<U4')

In [68]:
arr = np.array([1, 2, 3, 4, 5])
labels = np.vectorize(even_odd)(arr)

for val, label in zip(arr, labels):
    print(f"{val} is {label}")

1 is Odd
2 is Even
3 is Odd
4 is Even
5 is Odd


In [75]:
def describe(x):
    return x, "Even" if x % 2 == 0 else "Odd"

vfunc = np.vectorize(describe)
result = vfunc(np.array([1, 2, 3, 4]))
print("Result: ", result)
values, labels = zip(result)
print(values)  # (1, 2, 3, 4)
print(labels)  # ('Odd', 'Even', 'Odd', 'Even')

Result:  (array([1, 2, 3, 4]), array(['Odd', 'Even', 'Odd', 'Even'], dtype='<U4'))
(array([1, 2, 3, 4]),)
(array(['Odd', 'Even', 'Odd', 'Even'], dtype='<U4'),)


In [76]:
import numpy as np
import pandas as pd

# Define the function that returns a tuple
def describe(x):
    return x, "Even" if x % 2 == 0 else "Odd"

# Vectorize the function and specify output types
# otypes=[int, str] tells NumPy to expect two outputs: one int, one string
vfunc = np.vectorize(describe, otypes=[int, str])

# Apply to a NumPy array
values, labels = vfunc(np.array([1, 2, 3, 4, 5]))

# Print the separate arrays
print("Values:", values)   # Output: array([1, 2, 3, 4, 5])
print("Labels:", labels)   # Output: array(['Odd', 'Even', 'Odd', 'Even', 'Odd'])

# Optional: Convert to a pandas DataFrame for tabular view
df = pd.DataFrame({"Value": values, "Label": labels})
print("\nDataFrame:\n", df)

Values: [1 2 3 4 5]
Labels: ['Odd' 'Even' 'Odd' 'Even' 'Odd']

DataFrame:
    Value Label
0      1   Odd
1      2  Even
2      3   Odd
3      4  Even
4      5   Odd


In [80]:
import numpy as np

def describe(x):
    return x, "Even" if x % 2 == 0 else "Odd"

# Apply the function using a list comprehension
result = np.array([describe(x) for x in np.array([1, 2, 3, 4])], dtype=object)

print("Result:", result)

Result: [[1 'Odd']
 [2 'Even']
 [3 'Odd']
 [4 'Even']]


In [81]:
import numpy as np

def describe(x):
    return (x, "Even" if x % 2 == 0 else "Odd")  # 👈 Wrap in parentheses to force tuple

# Build a list of tuples
tuple_list = [describe(x) for x in [1, 2, 3, 4]]

# Convert to NumPy array of objects
result = np.array(tuple_list, dtype=object)

print("Result:", result)

Result: [[1 'Odd']
 [2 'Even']
 [3 'Odd']
 [4 'Even']]


In [90]:
def stats(x):
    return x, x**2, x % 2 == 0

vstats = np.vectorize(stats)
result = vstats(np.array([1, 2, 3]))
print(result)
print(type(result))
Org, Sqr, Bool = result
print(Org)
print(Sqr)
print(Bool)
print(zip(result))

(array([1, 2, 3]), array([1, 4, 9]), array([False,  True, False]))
<class 'tuple'>
[1 2 3]
[1 4 9]
[False  True False]


In [91]:
import numpy as np

def add_prefix(name):
    return f"Mr. {name}"

ufunc_prefix = np.frompyfunc(add_prefix, 1, 1)

names = np.array(["Lokesh", "Arjun", "Ravi"])
formatted = ufunc_prefix(names)

print(formatted)
# Output: ['Mr. Lokesh' 'Mr. Arjun' 'Mr. Ravi']

['Mr. Lokesh' 'Mr. Arjun' 'Mr. Ravi']


In [94]:
def diff_abs(x, y):
    return x, y, abs(x - y)

ufunc_diff = np.frompyfunc(diff_abs, 2, 3)

a = np.array([10, 5, 3])
b = np.array([3, 7, 3])

result = ufunc_diff(a, b)
print(result)
source, target, output = result
print("a: ", source)
print("b: ", target)
print("Output: ", output)

(array([10, 5, 3], dtype=object), array([3, 7, 3], dtype=object), array([7, 2, 0], dtype=object))
a:  [10 5 3]
b:  [3 7 3]
Output:  [7 2 0]


In [100]:
import numpy as np

employee_dtype = np.dtype([
    ('id', 'i4'),         # 4-byte integer
    ('name', 'U10'),      # Unicode string of max length 10
    ('salary', 'f4')      # 4-byte float
])

employees = np.array([
    (101, 'Lokesh', 75000.0),
    (102, 'Arjun', 68000.0),
    (103, 'Ravi', 72000.0)
], dtype=employee_dtype)

print(employees)
print(type(employees))
print(np.ndim(employees))
print(employees['name'])
print(employees[employees['salary'] > 70000])

[(101, 'Lokesh', 75000.) (102, 'Arjun', 68000.) (103, 'Ravi', 72000.)]
<class 'numpy.ndarray'>
1
['Lokesh' 'Arjun' 'Ravi']
[(101, 'Lokesh', 75000.) (103, 'Ravi', 72000.)]


In [108]:
employee_dtype = np.dtype([
    ('id', 'i4'),
    ('name', 'U10'),
    ('salary', 'f4'),
    ('bonus', 'f4')   
])

employees = np.array([
    (1, 'Lokesh', 95000, 5000),
    (2, 'Karthik', 200000, 50000),
    (3, 'Ravi', 45000, 3000),
    (4, 'Kranti', 70000, 15000),
    (5, 'Naga', 20000, 60000)
], dtype = employee_dtype)

print(employees[employees['salary'] + employees['bonus'] > 80000])

[(1, 'Lokesh',  95000.,  5000.) (2, 'Karthik', 200000., 50000.)
 (4, 'Kranti',  70000., 15000.)]


In [110]:
import numpy as np

# Step 1: Define structured dtype
employee_dtype = np.dtype([
    ('id', 'i4'),
    ('name', 'U10'),
    ('salary', 'f4'),
    ('bonus', 'f4')
])

# Step 2: Create structured array
employees = np.array([
    (1, 'Lokesh', 95000, 5000),
    (2, 'Karthik', 200000, 50000),
    (3, 'Ravi', 45000, 3000),
    (4, 'Kranti', 70000, 15000),
    (5, 'Naga', 20000, 60000)
], dtype=employee_dtype)

# Step 3: Compute total compensation
total_comp = employees['salary'] + employees['bonus']
print("Total_Comp: ", total_comp)

# Step 4: Filter employees with total > 80000
mask = total_comp > 80000
print("Mask: ", mask)
filtered = employees[mask]
print("Filtered: ", filtered)

# Step 5: Print names and total compensation
print("Employees with total compensation > ₹80,000:")
for emp, comp in zip(filtered, total_comp[mask]):
    print(f"{emp['name']}: ₹{comp:.2f}")

# Step 6: Sort by total compensation (descending)
sorted_indices = np.argsort(total_comp[mask])[::-1]
sorted_filtered = filtered[sorted_indices]
sorted_comp = total_comp[mask][sorted_indices]

print("\nSorted by total compensation:")
for emp, comp in zip(sorted_filtered, sorted_comp):
    print(f"{emp['name']}: ₹{comp:.2f}")

Total_Comp:  [100000. 250000.  48000.  85000.  80000.]
Mask:  [ True  True False  True False]
Filtered:  [(1, 'Lokesh',  95000.,  5000.) (2, 'Karthik', 200000., 50000.)
 (4, 'Kranti',  70000., 15000.)]
Employees with total compensation > ₹80,000:
Lokesh: ₹100000.00
Karthik: ₹250000.00
Kranti: ₹85000.00

Sorted by total compensation:
Karthik: ₹250000.00
Lokesh: ₹100000.00
Kranti: ₹85000.00


In [10]:
import numpy as np

array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]], dtype = np.float32)
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]], dtype = np.float32)

In [8]:
np.mean(array_2D, axis = 1)

array([40., 65., 33.])

In [9]:
np.mean(array_3D, axis = 0)

array([[ 6. ,  7. ,  8. ,  9. , 10. ],
       [31. , 36.5, 42. , 47.5, 28. ]])